language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
services:
  - mongodb
  - elasticsearch
before_script:
  - cp config/mongoid.yml.deploy config/mongoid.yml
  - cp config/elasticsearch.yml.deploy config/elasticsearch.yml
script:
  - bundle exec rake
  - bundle exec rake rubocop
