version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      cache_from:
        - ${DOCKER_IMAGE_CACHE_FROM:-ghcr.io/nrel/api-umbrella:dev-env-main}
    entrypoint: /app/docker/dev/docker-entrypoint
    command: /app/docker/dev/docker-start
    volumes:
      - .:/app
      - build_cache:/build
    environment:
      HTTP_PORT: 8100
      HTTPS_PORT: 8101
    ports:
      - "8100:8100"
      - "8101:8101"
      - "14050:14050"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
volumes:
  build_cache:
