version: "2.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - build_cache:/build
    tmpfs:
      # Mount the ember-cli tmp directory as a tmpfs partition for better
      # performance.
      - /app/src/api-umbrella/admin-ui/tmp:rw,size=128m,mode=1777
    environment:
      HTTP_PORT: 8200
      HTTPS_PORT: 8201
      SECRET_KEY: for-development-not-secure
    ports:
      - "8200:8200"
      - "8201:8201"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
volumes:
  build_cache:
