version: "2.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - build_cache:/build
    environment:
      HTTP_PORT: 8200
      HTTPS_PORT: 8201
      SECRET_KEY: for-development-not-secure
    ports:
      - "8200:8200"
      - "8201:8201"
      - "14011:14011"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
  # mongo:
  #   image: mongo:3.2
volumes:
  build_cache:
