version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - build_cache:/build
    environment:
      HTTP_PORT: 8100
      HTTPS_PORT: 8101
    ports:
      - "8100:8100"
      - "8101:8101"
volumes:
  build_cache:
