version: "2"

output: prefixed

tasks:
  deps:bundler:
    deps:
      - deps:rubygems
    cmds:
      - ./tasks/deps/bundler
    sources:
      - ./build/work/stamp/deps/rubygems
      - ./tasks/deps/bundler
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/bundler
    method: checksum

  deps:elasticsearch:
    cmds:
      - ./tasks/deps/elasticsearch
    sources:
      - ./tasks/deps/elasticsearch
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/elasticsearch
    method: checksum

  deps:geolitecity:
    cmds:
      - ./tasks/deps/geolitecity
    sources:
      - ./tasks/deps/geolitecity
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/geolitecity
    method: none

  deps:golang:
    cmds:
      - ./tasks/deps/golang
    sources:
      - ./tasks/deps/golang
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/golang
    method: checksum

  deps:libcidr:
    cmds:
      - ./tasks/deps/libcidr
    sources:
      - ./tasks/deps/libcidr
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/libcidr
    method: checksum

  deps:libestr:
    cmds:
      - ./tasks/deps/libestr
    sources:
      - ./tasks/deps/libestr
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/libestr
    method: checksum

  deps:libfastjson:
    cmds:
      - ./tasks/deps/libfastjson
    sources:
      - ./tasks/deps/libfastjson
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/libfastjson
    method: checksum

  deps:libgeoip:
    cmds:
      - ./tasks/deps/libgeoip
    sources:
      - ./tasks/deps/libgeoip
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/libgeoip
    method: checksum

  deps:luarocks:
    deps:
      - deps:openresty
    cmds:
      - ./tasks/deps/luarocks
    sources:
      - ./build/work/stamp/deps/openresty
      - ./tasks/deps/luarocks
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/luarocks
    method: checksum

  deps:mongodb:
    cmds:
      - ./tasks/deps/mongodb
    sources:
      - ./tasks/deps/mongodb
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/mongodb
    method: checksum

  deps:mora:
    deps:
      - deps:golang
    cmds:
      - ./tasks/deps/mora
    sources:
      - ./build/work/stamp/deps/golang
      - ./tasks/deps/mora
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/mora
    method: checksum

  deps:openresty:
    deps:
      - deps:libgeoip
    cmds:
      - ./tasks/deps/openresty
    sources:
      - ./build/work/stamp/deps/libgeoip
      - ./tasks/deps/openresty
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/openresty
    method: checksum

  deps:perp:
    cmds:
      - ./tasks/deps/perp
    sources:
      - ./tasks/deps/perp
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/perp
    method: checksum

  deps:rsyslog:
    deps:
      - deps:libestr
      - deps:libfastjson
    cmds:
      - ./tasks/deps/rsyslog
    sources:
      - ./build/work/stamp/deps/libestr
      - ./build/work/stamp/deps/libfastjson
      - ./tasks/deps/rsyslog
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/rsyslog
    method: checksum

  deps:ruby:
    cmds:
      - ./tasks/deps/ruby
    sources:
      - ./tasks/deps/ruby
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/ruby
    method: checksum

  deps:rubygems:
    deps:
      - deps:ruby
    cmds:
      - ./tasks/deps/rubygems
    sources:
      - ./build/work/stamp/deps/ruby
      - ./tasks/deps/rubygems
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/rubygems
    method: checksum

  deps:runit_svlogd:
    cmds:
      - ./tasks/deps/runit_svlogd
    sources:
      - ./tasks/deps/runit_svlogd
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/runit_svlogd
    method: checksum

  deps:trafficserver:
    cmds:
      - ./tasks/deps/trafficserver
    sources:
      - ./tasks/deps/trafficserver
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/trafficserver
    method: checksum

  deps:
    cmds:
      - task: deps:bundler
      - task: deps:elasticsearch
      - task: deps:geolitecity
      - task: deps:libcidr
      - task: deps:luarocks
      - task: deps:mongodb
      - task: deps:mora
      - task: deps:openresty
      - task: deps:perp
      - task: deps:rsyslog
      - task: deps:runit_svlogd
      - task: deps:trafficserver

  build-deps:nodejs:
    cmds:
      - ./tasks/build-deps/nodejs
    sources:
      - ./tasks/build-deps/nodejs
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/build-deps/nodejs
    method: checksum

  build-deps:yarn:
    deps:
      - build-deps:nodejs
    cmds:
      - ./tasks/build-deps/yarn
    sources:
      - ./build/work/stamp/build-deps/nodejs
      - ./tasks/build-deps/yarn
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/build-deps/yarn
    method: checksum

  build-deps:
    cmds:
      - task: build-deps:yarn

  app-deps:admin-ui:yarn:
    deps:
      - build-deps:yarn
    cmds:
      - ./tasks/app-deps/admin-ui/yarn
    sources:
      - ./build/work/stamp/build-deps/yarn
      - ./src/api-umbrella/admin-ui/package.json
      - ./src/api-umbrella/admin-ui/yarn.lock
      - ./tasks/app-deps/admin-ui/yarn
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/admin-ui/yarn
    method: checksum

  app-deps:lua:argparse:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/argparse
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/argparse
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/argparse
    method: checksum

  app-deps:lua:cmsgpack:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/cmsgpack
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/cmsgpack
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/cmsgpack
    method: checksum

  app-deps:lua:iconv:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/iconv
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/iconv
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/iconv
    method: checksum

  app-deps:lua:icu-date:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/icu-date
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/icu-date
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/icu-date
    method: checksum

  app-deps:lua:inspect:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/inspect
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/inspect
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/inspect
    method: checksum

  app-deps:lua:libcidr-ffi:
    deps:
      - deps:libcidr
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/libcidr-ffi
    sources:
      - ./build/work/stamp/deps/libcidr
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/libcidr-ffi
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/libcidr-ffi
    method: checksum


  app-deps:lua:luaposix:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/luaposix
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/luaposix
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/luaposix
    method: checksum

  app-deps:lua:luasocket:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/luasocket
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/luasocket
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/luasocket
    method: checksum

  app-deps:lua:lustache:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/lustache
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/lustache
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/lustache
    method: checksum

  app-deps:lua:lyaml:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/lyaml
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/lyaml
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/lyaml
    method: checksum

  app-deps:lua:penlight:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/penlight
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/penlight
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/penlight
    method: checksum

  app-deps:lua:resty-http:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-http
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-http
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-http
    method: checksum

  app-deps:lua:resty-logger-socket:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-logger-socket
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-logger-socket
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-logger-socket
    method: checksum

  app-deps:lua:resty-shcache:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-shcache
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-shcache
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-shcache
    method: checksum

  app-deps:lua:resty-txid:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-txid
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-txid
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-txid
    method: checksum

  app-deps:lua:resty-uuid:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-uuid
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-uuid
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-uuid
    method: checksum

  app-deps:web-app:bundle:
    deps:
      - deps:bundler
    cmds:
      - ./tasks/app-deps/web-app/bundle
    sources:
      - ./build/work/stamp/deps/bundler
      - ./src/api-umbrella/web-app/Gemfile
      - ./src/api-umbrella/web-app/Gemfile.lock
      - ./tasks/app-deps/web-app/bundle
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/web-app/bundle
    method: checksum

  app-deps:
    cmds:
      - task: app-deps:admin-ui:yarn
      - task: app-deps:lua:argparse
      - task: app-deps:lua:cmsgpack
      - task: app-deps:lua:iconv
      - task: app-deps:lua:icu-date
      - task: app-deps:lua:inspect
      - task: app-deps:lua:libcidr-ffi
      - task: app-deps:lua:luaposix
      - task: app-deps:lua:luasocket
      - task: app-deps:lua:lustache
      - task: app-deps:lua:lyaml
      - task: app-deps:lua:penlight
      - task: app-deps:lua:resty-http
      - task: app-deps:lua:resty-logger-socket
      - task: app-deps:lua:resty-shcache
      - task: app-deps:lua:resty-txid
      - task: app-deps:lua:resty-uuid
      - task: app-deps:web-app:bundle

  app:admin-ui:build:
    deps:
      - app-deps:admin-ui:yarn
    cmds:
      - ./tasks/app/admin-ui/build
    sources:
      - ./build/work/stamp/app-deps/admin-ui/yarn
      - ./src/api-umbrella/admin-ui/app/**/*.hbs
      - ./src/api-umbrella/admin-ui/app/**/*.html
      - ./src/api-umbrella/admin-ui/app/**/*.js
      - ./src/api-umbrella/admin-ui/app/**/*.scss
      - ./src/api-umbrella/admin-ui/config/**/*.js
      - ./src/api-umbrella/admin-ui/ember-cli-build.js
      - ./src/api-umbrella/admin-ui/lib/**/*.js
      - ./tasks/app/admin-ui/build
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app/admin-ui/build
    method: checksum

  app:static-site:
    deps:
      - build-deps:nodejs
      - deps:bundler
    cmds:
      - ./tasks/app/static-site
    sources:
      - ./build/work/stamp/build-deps/nodejs
      - ./build/work/stamp/deps/bundler
      - ./tasks/app/static-site
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app/static-site
    method: checksum

  app:web-app:precompile:
    deps:
      - app-deps:web-app:bundle
    cmds:
      - ./tasks/app/web-app/precompile
    sources:
      - ./build/work/stamp/app-deps/web-app/bundle
      - ./src/api-umbrella/web-app/app/assets/**/*.css
      - ./src/api-umbrella/web-app/app/assets/**/*.erb
      - ./src/api-umbrella/web-app/app/assets/**/*.js
      - ./src/api-umbrella/web-app/app/assets/**/*.scss
      - ./tasks/app/web-app/precompile
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app/web-app/precompile
    method: checksum

  app:
    cmds:
      - task: app:admin-ui:build
      - task: app:static-site
      - task: app:web-app:precompile

  all:
    cmds:
      - task: app
      - task: app-deps
      - task: build-deps
      - task: deps

  test-deps:bundle:
    deps:
      - deps:bundler
    cmds:
      - ./tasks/test-deps/bundle
    sources:
      - ./build/work/stamp/deps/bundler
      - ./Gemfile
      - ./Gemfile.lock
      - ./tasks/test-deps/bundle
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/bundle
    method: checksum

  test-deps:
    cmds:
      - task: test-deps:bundle

  lint:js:
    dir: ./src/api-umbrella/admin-ui
    cmds:
      - yarn run lint:js

  lint:lua:
    cmds:
      - build/work/test-env/vendor/bin/luacheck $(git ls-files | grep '\.lua$')

  lint:ruby:
    cmds:
      - bundle exec rubocop $(git ls-files | grep -E '(Rakefile|\.(rb|rake))$')

  lint:shell:
    cmds:
      - ./tasks/lint/shell

  lint:
    cmds:
      - task: lint:js
      - task: lint:lua
      - task: lint:ruby
      - task: lint:shell

  default:
    cmds:
      - task: all
