version: 2
jobs:
  build:
    parallelism: 3
    working_directory: /app
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      # Install any system package dependencies.
      - run: env INSTALL_TEST_DEPENDENCIES=true ./build/scripts/install_build_dependencies
      - restore_cache:
          # CircleCI's prefix based matching will mean the cache from the last
          # cache for this branch will be restored.
          key: cache-build-deps-v2-{{ .Branch }}-{{ arch }}-
      # The bootstrap's "task" file will be cached on subsequent runs, but due
      # to the reliance on timestamps, this fact might not get picked up in the
      # CI environment. So if a stamp file exists for the initial bootstrap
      # process, re-touch it to prevent re-downloads.
      - run: touch -c build/work/stamp/bootstrap-*
      # Build all the API Umbrella software dependencies.
      - run: ./configure
      - run: make all test-deps
      # Cache the staged build data and task checksums of what's been
      # completed. But explicitly don't cache most of the build/work/tasks/*
      # data, since that contains a lot of the intermediate build files, which
      # can  significantly increase the cache size.
      - save_cache:
          key: cache-build-deps-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ arch }}-{{ epoch }}
          paths:
            - .task
            - build/work/dev-env
            - build/work/stage
            - build/work/stamp
            - build/work/task
            - build/work/tasks/app-deps/admin-ui/yarn/_persist
            - build/work/tasks/app-deps/web-app/bundle/_persist
            - build/work/tasks/test-deps/bundle/_persist
            - build/work/test-env
      - run: make test:circle-ci
      - store_test_results:
          path: test/tmp/reports
      - store_artifacts:
          path: test/tmp/run/api-umbrella-root/var/log
      - store_artifacts:
          path: test/tmp/capybara
