defaults: &defaults
  clients:
    default:
      uri: <%= ApiUmbrellaConfig[:mongodb][:url] %>

development:
  <<: *defaults

test:
  clients:
    default:
      uri: <%= ApiUmbrellaConfig[:mongodb][:url] %>
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  <<: *defaults
