stylesheets:
  public:
    - public/stylesheets/yui/reset.css
    - public/stylesheets/yui/base.css
    - public/stylesheets/yui/fonts.css
    - public/stylesheets/grid.css
    - public/stylesheets/nrel.css
    - public/stylesheets/pygments.css
    - public/stylesheets/pygments_overrides.css
    - public/stylesheets/doc_service.css
    - public/stylesheets/buttons.css
    - public/stylesheets/sprite.css
    - public/stylesheets/public.css

  admin:
    - public/stylesheets/yui/reset.css
    - public/stylesheets/yui/base.css
    - public/stylesheets/yui/fonts.css
    - public/stylesheets/admin/fluid_grid.css
    - public/stylesheets/admin/sprite.css
    - public/stylesheets/admin/base.css

javascripts:
  public:
    - public/javascripts/jquery-1.6.2.js
    - public/javascripts/rails.validations.js
    - public/javascripts/TableOfContents/js/jquery.tableofcontents.js

  admin:
    - public/javascripts/jquery-1.6.2.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/rails.validations.js
    - public/javascripts/jQuery-Slugify-Plugin/jquery.slugify.js
    - public/javascripts/application.js
