# Use ERB to include the contents of our shared YAML database config file.
<%= IO.read(File.join(AUTH_PROXY_ROOT, "config", "shared_config", "database.yml")) %>

# Define the default connections we want to use.
development:
  <<: *web_service_framework_api_development

staging:
  <<: *web_service_framework_api_staging

production:
  <<: *web_service_framework_api_production
