# Use ERB to include the contents of our shared YAML database config file.
<%= IO.read("/etc/db_config/database.yml") %>

# Define the default connections we want to use.
development:
  <<: *developer_api_development

staging:
  <<: *developer_api_staging

production:
  <<: *developer_api_production
