http_port: 9000
https_port: 9001
redis:
  host: 127.0.0.1
  port: 50379
nginx:
  workers: 4
gatekeeper:
  workers: 4
varnish:
  port: 51700
mongodb:
  url: "mongodb://127.0.0.1:50217/api_umbrella_development"
  options:
    server:
      socketOptions:
        keepAlive: 500
    replset:
      socketOptions:
        keepAlive: 500
  embedded_server_config:
    port: 50217
    dbpath: /tmp/db/mongodb
elasticsearch:
  embedded_server_config:
    path_data: /tmp/db/elasticsearch
    http_port: 50200
    transport_tcp_port: 50300
