app_env: production
services:
  - general_db
  - log_db
  - router
  - web
user: api-umbrella
group: api-umbrella
rlimits:
  nofile: 100000
  nproc: 20000
http_port: 80
https_port: 443
root_dir: /opt/api-umbrella
etc_dir: /opt/api-umbrella/etc
log_dir: /opt/api-umbrella/var/log
run_dir: /opt/api-umbrella/var/run
tmp_dir: /opt/api-umbrella/var/tmp
db_dir: /opt/api-umbrella/var/db
redis:
  host: 127.0.0.1
  port: 14000
beanstalkd:
  host: 127.0.0.1
  port: 14005
dnsmasq:
  port: 14007
nginx:
  workers: 4
  worker_connections: 8192
gatekeeper:
  workers: 4
  host: 127.0.0.1
  dir: /opt/api-umbrella/embedded/apps/gatekeeper/current
  starting_port: 14050
  default_frontend_host:
  api_key_methods:
    - header
    - getParam
    - basicAuthUsername
  target: "127.0.0.1:14010"
varnish:
  host: 127.0.0.1
  port: 14010
trafficserver:
  host: 127.0.0.1
  port: 14009
  storage:
    size: 256M
  # install_root: /opt/api-umbrella/embedded
  install_root: "/opt/trafficserver"
web:
  host: 127.0.0.1
  port: 14012
  dir: /opt/api-umbrella/embedded/apps/web/current
  rails_secret_token:
  devise_secret_key:
  puma:
    bind: "unix:///opt/api-umbrella/var/run/puma.sock"
    workers: 2
    min_threads: 2
    max_threads: 24
  admin:
    initial_superusers: []
    auth_strategies:
      enabled:
        - github
        - google
        - persona
      facebook:
        client_id:
        client_secret:
      github:
        client_id:
        client_secret:
      google:
        client_id:
        client_secret:
static_site:
  host: 127.0.0.1
  port: 14013
  host_header:
  dir: /opt/api-umbrella/embedded/apps/static-site/current
router:
  api_backends:
    host: 127.0.0.1
    port: 14011
  dir: /opt/api-umbrella/embedded/apps/router/current
  trusted_proxies: []
  global_rate_limits:
    ip_rate: "100r/s"
    ip_burst: 200
    ip_rate_size: 8m
    ip_connections: 50
    ip_connections_size: 5m
  log_listener:
    port: 14006
supervisord:
  inet_http_server:
    host: 127.0.0.1
    port: 14004
hosts:
  - hostname: localhost
    default: true
dns_resolver:
  minimum_ttl: 40
  reload_buffer_time: 40
mongodb:
  url: "mongodb://127.0.0.1:14001/api_umbrella"
  options:
    server:
      socketOptions:
        keepAlive: 500
    replset:
      socketOptions:
        keepAlive: 500
  embedded_server_config:
    processManagement:
      fork: false
    net:
      port: 14001
elasticsearch:
  hosts:
    - "http://127.0.0.1:14002"
  embedded_server_env:
    heap_size: 512m
  embedded_server_config:
    http:
      port: 14002
    transport:
      tcp:
        port: 14003
    cluster:
      name: api-umbrella
    indices:
      fielddata:
        cache:
          size: 40%
      breaker:
        fielddata:
          limit: 60%
    # Disable Groovy scripting for security: CVE-2015-1427
    script:
      groovy:
        sandbox:
          enabled: false
log_template_version: v1
strip_cookies:
  - ^__utm.*$
  - ^_ga$
  - ^is_returning$
default_host: localhost
site_name: API Umbrella
apiSettings:
  require_https: required_return_error
  rate_limits:
    - duration: 1000
      accuracy: 500
      limit_by: ip
      limit: 50
      distributed: false
    - duration: 1000
      accuracy: 500
      limit_by: apiKey
      limit: 20
      distributed: false
    - duration: 15000
      accuracy: 1000
      limit_by: ip
      limit: 250
      distributed: true
    - duration: 15000
      accuracy: 1000
      limit_by: apiKey
      limit: 150
      distributed: true
    - duration: 3600000
      accuracy: 60000
      limit_by: apiKey
      limit: 1000
      distributed: true
      response_headers: true
  error_templates:
    json: |
      {
        "error": {
          "code": {{code}},
          "message": {{message}}
        }
      }
    xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <response>
        <error>
          <code>{{code}}</code>
          <message>{{message}}</message>
        </error>
      </response>
    csv: |
      Error Code,Error Message
      {{code}},{{message}}
    html: |
      <html>
        <body>
          <h1>{{code}}</h1>
          <p>{{message}}</p>
        </body>
      </html>
  error_data:
    not_found:
      status_code: 404
      code: NOT_FOUND
      message: The requested URL was not found on this server.
    api_key_missing:
      status_code: 403
      code: API_KEY_MISSING
      message: No api_key was supplied. Get one at {{baseUrl}}
    api_key_invalid:
      status_code: 403
      code: API_KEY_INVALID
      message: An invalid api_key was supplied. Get one at {{baseUrl}}
    api_key_disabled:
      status_code: 403
      code: API_KEY_DISABLED
      message: The api_key supplied has been disabled. Contact us at {{baseUrl}}/contact for assistance
    api_key_unauthorized:
      status_code: 403
      code: API_KEY_UNAUTHORIZED
      message: The api_key supplied is not authorized to access the given service. Contact us at {{baseUrl}}/contact for assistance
    over_rate_limit:
      status_code: 429
      code: OVER_RATE_LIMIT
      message: You have exceeded your rate limit. Try again later or contact us at {{baseUrl}}/contact for assistance
    internal_server_error:
      status_code: 500
      code: INTERNAL_SERVER_ERROR
      message: An unexpected error has occurred. Try again later or contact us at {{baseUrl}}/contact for assistance
    https_required:
      status_code: 400
      code: HTTPS_REQUIRED
      message: "Requests must be made over HTTPS. Try accessing the API at: {{httpsUrl}}"
