development:
  host: devdev-db.nrel.gov
  database: web_service_framework_development_rails3

test:
  host: devdev-db.nrel.gov
  database: web_service_framework_test_rails3

staging:
  host: dev-stage-db.nrel.gov
  database: web_service_framework_staging_rails3

production:
  host: developerdb.nrel.gov
  database: web_service_framework_production_rails3
