# Use ERB to include the contents of our shared YAML database config file.
<%= IO.read("/etc/db_config/database.yml") %>

development:
  <<: *developer_redis_development

test:
  <<: *developer_redis_test

staging_int:
  <<: *developer_redis_staging_int

production:
  <<: *developer_redis_production
