baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site
params:
  githubRepoUrl: https://github.com/NREL/api-umbrella
  apiUmbrellaApiKey:
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
